language: c

script: asdf plugin-test docker-machine https://github.com/virtualstaticvoid/asdf-docker-machine.git

before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh

os:
  - linux
